import java.io.FileWriter;
import java.io.IOException;

public class AppV3 {

    public static void main(String[] args) {

        System.out.println("=================================");
        System.out.println("        VERSION 3 DEMO           ");
        System.out.println("=================================");

        String buildName = "DefaultBuild";

        if (args.length > 0) {
            buildName = args[0];
        }

        System.out.println("BUILD_NAME Parameter: " + buildName);

        try {
            FileWriter writer = new FileWriter("build_output.txt");

            writer.write("Build Name: " + buildName + "\n");
            writer.write("Build created successfully.\n");
            writer.write("This file was generated by Jenkins.\n");
            writer.write("Pipeline execution completed.\n");

            writer.close();

            System.out.println("File 'build_output.txt' created successfully!");

        } catch (IOException e) {
            System.out.println("Error while creating file.");
            e.printStackTrace();
        }

        System.out.println("Execution Finished.");
        System.out.println("=================================");
    }
}